# Generated by Django 3.2.9 on 2021-12-01 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(editable=False, max_length=10, unique=True)),
                ('descrição', models.CharField(blank=True, max_length=150)),
                ('modificador', models.CharField(max_length=150)),
                ('criado', models.DateField(auto_now_add=True)),
                ('atualizado', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Arquivos',
            },
        ),
        migrations.CreateModel(
            name='Secção',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=10, unique=True)),
                ('descrição', models.CharField(blank=True, max_length=150)),
                ('modificador', models.CharField(max_length=150)),
                ('criado', models.DateField(auto_now_add=True)),
                ('atualizado', models.DateField(auto_now=True)),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Secções',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('file', models.FileField(max_length=200, null=True, upload_to='documents/%d/%m/%Y')),
                ('modificador', models.CharField(max_length=150)),
                ('adicionado', models.DateField(auto_now_add=True)),
                ('atualizado', models.DateField(auto_now=True)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.arquivo')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Caçifo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(editable=False, max_length=10, unique=True)),
                ('descrição', models.CharField(blank=True, max_length=150)),
                ('modificador', models.CharField(max_length=150)),
                ('criado', models.DateField(auto_now_add=True)),
                ('atualizado', models.DateField(auto_now=True)),
                ('secção', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.secção')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Caçifos',
            },
        ),
        migrations.AddField(
            model_name='arquivo',
            name='caçifo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.caçifo'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
