"""
Django settings for adminGex project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import moneyed
from moneyed.classes import CURRENCIES
from moneyed.localization import _FORMATTER
from decimal import ROUND_HALF_EVEN

import django_heroku

MT = moneyed.add_currency(
    code = 'MT ',
    numeric = '508',
    name = 'Metical Moçambicano',
    countries=('MOZAMBIQUE',)
)

_FORMATTER.add_sign_definition(
    'default',
    MT,
    prefix='MT. '
)

_FORMATTER.add_formatting_definition(
    'es_MZN',
    group_separator=".", group_size=3, decimal_point=",",
    positive_sign="", trailing_positive_sign="", 
    negative_sign="-", trailing_negative_sign="-",
    rounding_method=ROUND_HALF_EVEN
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bp)%(0+mplh-j_6z7pe35wf#l2v_3-t_ft^39ic1%)*v9^5x_j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.43.132', '*',]


# Application definition

SHARED_APPS = (
    'django_tenants',
    'django.contrib.contenttypes',
    'empresa',
    'djmoney',
    'users',


    #Built-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #User model
    

)
    


TENANT_APPS = (
    #Built-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'djmoney',
    'producto',
    'caixa',
    'empresa',
    'users',
    'clientes',
)

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'adminGex.urls'
PUBLIC_SCHEMA_URLCONF = 'adminGex.urls_public'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'adminGex.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': 'd97in232gf8th5',
        'USER': 'vuhgmufrvkzsri',
        'PASSWORD': 'c3ee821fcc03de379ba1c419ec7eb75b5090c0d0a97a2f4137b9e0561d1ea92b',
        'HOST': 'ec2-34-195-69-118.compute-1.amazonaws.com',
        'POST': '5432',
    }
}

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

TENANT_MODEL = "empresa.Customer"
TENANT_DOMAIN_MODEL = "empresa.Domain"


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'
STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "users.Profile"
LOGIN_URL = '/profile/entrar'

SHOW_PUBLIC_IF_NO_TENANT_FOUND = True

django_heroku.settings(locals())

